INSERT INTO productions (id, name, description, genre, image_url, length, production_type, rating, rent_price, video_url, year)
VALUES (1, 'Alien: Romulus', 'While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.', 'HORROR', 'https://wiziwiz.com/wp-content/uploads/2024/06/wiziwiz-alien-romulus-poster-.jpg', '132', 'MOVIE', '5', '10', 'x0XDEhP4MQs', '2024'),
       (2, 'Stalker', 'Stalker (Russian: Сталкер, IPA: is a 1979 Soviet science fiction film directed by Andrei Tarkovsky with a screenplay written by Arkady and Boris Strugatsky, loosely based on their 1972 novel Roadside Picnic. The film tells the story of an expedition led by a figure known as the "Stalker" (Alexander Kaidanovsky), who guides his two clients—a melancholic writer (Anatoly Solonitsyn) seeking inspiration, and a professor (Nikolai Grinko) seeking scientific discovery—through a hazardous wasteland to a mysterious restricted site known simply as the "Zone", where there supposedly exists a room which grants a person''s innermost desires. The film combines elements of science fiction and fantasy with dramatic philosophical, and psychological themes.', 'ADVENTURE', 'https://www.sensesofcinema.com/wp-content/uploads/2014/02/stalker-640x400.jpg', '184', 'MOVIE', '5', '4', 'YuOnfQd-aTw', '1979'),
       (3, 'Forrest Gump', 'The film follows the life of an Alabama man named Forrest Gump (Hanks) and his experiences in the 20th-century United States. Principal photography took place between August and December 1993, mainly in Georgia, North Carolina and South Carolina. Extensive visual effects were used to incorporate Hanks into archived footage and to develop other scenes. The soundtrack features songs reflecting the different periods seen in the film.', 'DRAMA', 'https://m.media-amazon.com/images/I/91++WV6FP4L._AC_UF894,1000_QL80_.jpg', '142', 'MOVIE', '5', '8', 'bLvqoHBptjg', '1994'),
       (4, 'Fight Club', 'Fight Club is a 1999 American film directed by David Fincher, and starring Brad Pitt, Edward Norton and Helena Bonham Carter. It is based on the 1996 novel by Chuck Palahniuk. Norton plays the unnamed narrator, who is discontented with his white-collar job. He forms a "fight club" with soap salesman Tyler Durden (Pitt), and becomes embroiled in a relationship with an impoverished but beguilingly attractive woman, Marla Singer (Bonham Carter).', 'DRAMA', 'https://m.media-amazon.com/images/M/MV5BMjk3NTYyMzc4Nl5BMl5BanBnXkFtZTcwODU3ODMzMw@@._V1_.jpg', '139', 'MOVIE', '5', '6', 'qtRKdVHc-cE', '1999'),
       (5, 'Gladiator', 'Crowe portrays the Roman general Maximus Decimus Meridius, who is betrayed when Commodus, the ambitious son of Emperor Marcus Aurelius, murders his father and seizes the throne. Reduced to slavery, Maximus becomes a gladiator and rises through the ranks of the arena, determined to avenge the murders of his family and the emperor.', 'ACTION', 'https://m.media-amazon.com/images/I/51GA6V6VE1L._AC_UF894,1000_QL80_.jpg', '153', 'MOVIE', '5', '4', 'P5ieIbInFpg', '2000'),
       (6, 'Oppenheimer', 'Oppenheimer is a 2023 epic biographical thriller drama film[a] written, directed, and produced by Christopher Nolan.[8] It follows the life of J. Robert Oppenheimer, the American theoretical physicist who helped develop the first nuclear weapons during World War II. Based on the 2005 biography American Prometheus by Kai Bird and Martin J. Sherwin, the film chronicles Oppenheimer''s studies, his direction of the Los Alamos Laboratory and his 1954 security hearing. Cillian Murphy stars as Oppenheimer, alongside Robert Downey Jr. ', 'HISTORICAL', 'https://images.indianexpress.com/2023/05/nolan-movie.jpg', '180', 'MOVIE', '5', '9', 'bK6ldnjE3Y0', '2023'),
       (7, 'Friends', 'Friends is an American television sitcom created by David Crane and Marta Kauffman, which aired on NBC from September 22, 1994, to May 6, 2004, lasting ten seasons.[1] With an ensemble cast starring Jennifer Aniston, Courteney Cox, Lisa Kudrow, Matt LeBlanc, Matthew Perry and David Schwimmer, the show revolves around six friends in their 20s and early 30s who live in Manhattan, New York City. The original executive producers were Kevin S. Bright, Kauffman, and Crane.', 'COMEDY', 'https://uniathenaprods3.uniathena.com/s3fs-public/insights-article/seriesreview-e2-80-9cfriends-e2-80-9d_0.jpg', '30', 'TV', '5', '10', 'IEEbUzffzrk&t=2s', '1994'),
       (8, 'Breaking Bad', 'Breaking Bad is an American crime drama television series created and produced by Vince Gilligan for AMC. Set and filmed in Albuquerque, New Mexico, the series follows Walter White (Bryan Cranston), an underpaid, dispirited high-school chemistry teacher struggling with a recent diagnosis of stage-three lung cancer.', 'ADVENTURE', 'https://ntvb.tmsimg.com/assets/p8696131_b_h10_aa.jpg?w=960&h=540', '45', 'TV', '4', '8', 'HhesaQXLuRY', '2008'),
       (9, 'Game of Thrones', 'Game of Thrones is an American fantasy drama television series created by David Benioff and D. B. Weiss for HBO. It is an adaptation of A Song of Ice and Fire, a series of fantasy novels by George R. R. Martin, the first of which is A Game of Thrones. The show premiered on HBO in the United States on April 17, 2011, and concluded on May 19, 2019, with 73 episodes broadcast over eight seasons.', 'FANTASY', 'https://assets-prd.ignimgs.com/2022/01/14/gameofthrones-allseasons-sq-1642120207458.jpg', '60', 'TV', '5', '7', 'bjqEWgDVPe0', '2011'),
       (10, 'The Office', 'The Office is an American mockumentary sitcom television series based on the 2001–2003 BBC series of the same name created by (and starring) Ricky Gervais and Stephen Merchant. Adapted for NBC by Greg Daniels, a veteran writer for Saturday Night Live, King of the Hill, and The Simpsons.', 'COMEDY', 'https://ntvb.tmsimg.com/assets/p7893514_b_h8_ab.jpg?w=960&h=540', '22', 'TV', '3', '5', 'tNcDHWpselE', '2005'),
       (11, 'Black Mirror', 'Black Mirror is a British anthology television series created by Charlie Brooker. The series explores various genres, with most episodes set in near-future dystopias containing sci-fi technology—a type of speculative fiction. The series is inspired by The Twilight Zone and uses the themes of technology and media to comment on contemporary social issues.', 'THRILLER', 'https://images.justwatch.com/poster/307079555/s332/season-6', '60', 'TV', '4', '9', 'V0XOApF5nLU', '2011'),
       (12, 'House', 'House (also called House, M.D.) is an American medical drama television series that originally ran on the Fox network for eight seasons, from November 16, 2004, to May 21, 2012. Its main character, Dr. Gregory House (Hugh Laurie), is an unconventional, misanthropic, cynical medical genius who, despite his dependence on pain medication, leads a team of diagnosticians at the fictional Princeton–Plainsboro Teaching Hospital (PPTH) in New Jersey.', 'DRAMA', 'https://pics.filmaffinity.com/house_m_d-469252061-large.jpg', '45', 'TV', '5', '3', 'MczMB8nU1sY', '2004');


